tarea3/condominio/urls.py
from django.urls import path, include
from . import views
app_name = 'condominio'

urlpatterns = [
    path('', views.index, name="index"),

]

tarea3/propietarios/urls.py
from django.urls import path, include
from . import views
app_name = 'propietarios'


urlpatterns = [
    path('', views.index, name="index"),
    path('registrar_propietario', views.registrar_propietario, name="registrar_propietario"),
]

tarea3/registros/urls.py
from django.urls import path
from . import views

app_name = 'registros'

urlpatterns = [
    path('', views.index, name='index'),
    path('registrar_entrada/', views.registrar_entrada, name='registrar_entrada'),
    path('registrar_salida/', views.registrar_salida, name='registrar_salida'),
]

tarea3/tarea3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('condominio.urls')),
    path('propietarios/', include('propietarios.urls')),
    path('vehiculos/', include('vehiculos.urls')),
    path('registros/', include('registros.urls')),
]

tarea3/vehiculos/urls.py
from django.urls import path
from . import views
app_name = 'vehiculos'

urlpatterns = [
    path('', views.index, name="index"),
    path('registrar/', views.registrar_vehiculo, name='registrar_vehiculo'),
]

tarea3/condominio/models.py
from django.db import models




tarea3/propietarios/models.py
from django.db import models

# Create your models here.
class Propietario(models.Model):
    nombre_completo = models.CharField(max_length=50)
    numero_apartamento = models.CharField(max_length=3)
    numero_telefono = models.CharField(max_length=9)
    email = models.EmailField(unique=True)

tarea3/registros/models.py
from django.db import models
from vehiculos.models import Vehiculo

class Registro(models.Model):
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    fecha_hora_entrada = models.DateTimeField(auto_now_add=True)
    fecha_hora_salida = models.DateTimeField(null=True, blank=True)

tarea3/vehiculos/models.py
from django.db import models
from propietarios.models import Propietario

# Create your models here.
class Vehiculo(models.Model):
    propietario = models.ForeignKey(Propietario, on_delete=models.CASCADE)
    matricula = models.CharField(max_length=7, unique=True)
    marca = models.CharField(max_length=30)
    modelo = models.CharField(max_length=30)
    color = models.CharField(max_length=30)

tarea3/condominio/views.py
from django.shortcuts import render
# Create your views here.


# vista principal

def index(request):
    return render(request, 'condominio/index.html')


tarea3/propietarios/views.py
from django.shortcuts import render,redirect
from .models import Propietario

# Create your views here.

#vista para la lista de propietarios

def index(request):
    propietarios = Propietario.objects.all()
    return render(request, 'propietarios/index.html', {'propietarios': propietarios})

def registrar_propietario(request):
    errors = []
    if request.method == 'POST':
        nombre_completo = request.POST.get('nombre_completo')
        numero_apartamento = request.POST.get('numero_apartamento')
        numero_telefono = request.POST.get('numero_telefono')
        email = request.POST.get('email')

        # Validaciones
        if not nombre_completo:
            errors.append('nombre no valido.')
        if not numero_apartamento:
            errors.append('numero de apartamento no valido.')
        if len(numero_telefono) != 9 or not numero_telefono.isdigit():
            errors.append('numero de telefono de 9 digitos.')
        if Propietario.objects.filter(email=email).exists():
            errors.append('Ya existe el correo electronico.')
        if not errors:
            # Se crea un nuevo propietario
            Propietario.objects.create(
                nombre_completo=nombre_completo,
                numero_apartamento=numero_apartamento,
                numero_telefono=numero_telefono,
                email=email
            )
            return redirect('propietarios:index')
        

    return render(request, 'propietarios/registro.html', {'errors': errors})

tarea3/registros/views.py
from django.shortcuts import render, redirect
from .models import Registro
from vehiculos.models import Vehiculo
from django.utils import timezone
from django.db.models import Q

def index(request):
    registros_entrada = Registro.objects.filter(fecha_hora_salida__isnull=False)
    registros_salida = Registro.objects.filter(fecha_hora_salida__isnull=True)
    return render(request, 'registros/index.html', {
        'registros_entrada': registros_entrada,
        'registros_salida': registros_salida
    })

def registrar_entrada(request):
    # conseguir los vehiculos que no tienen el registro y los que tienen fecha de salida
    vehiculos_entrantes = Vehiculo.objects.filter(
        Q(registro__isnull=True) | ~Q(registro__fecha_hora_salida__isnull=True)
    ).distinct()

    if request.method == 'POST':
        vehiculo_id = request.POST['vehiculo']
        vehiculo = Vehiculo.objects.get(id=vehiculo_id)
        
        # se crea el nuevo registro
        Registro.objects.create(vehiculo=vehiculo)
        
        return redirect('registros:index')

    return render(request, 'registros/registrar_entrada.html', {'vehiculos': vehiculos_entrantes})

def registrar_salida(request):
    # conseguir los registros sin fecha de salida y que tengan registros
    vehiculos_salida = Vehiculo.objects.filter(
        Q(registro__fecha_hora_salida__isnull=True) &
        ~Q(registro__isnull=True)
    ).distinct()

    if request.method == 'POST':
        matricula = request.POST['matricula']
        
        # buscar la matricula del vehiculo
        vehiculo = Vehiculo.objects.filter(matricula=matricula).first()
        
        # encontrar registro donde falta fecha de salida
        registro = Registro.objects.filter(vehiculo=vehiculo, fecha_hora_salida__isnull=True).first()
        
        # actualizar la hora de salida
        registro.fecha_hora_salida = timezone.now()
        registro.save()
        
        return redirect('registros:index')

    return render(request, 'registros/registrar_salida.html', {'vehiculos': vehiculos_salida})

tarea3/vehiculos/views.py
from django.shortcuts import render, redirect
from .models import Vehiculo
from propietarios.models import Propietario
# Create your views here.

# index de vehiculos

def index(request):
    vehiculos = Vehiculo.objects.all()
    return render(request, 'vehiculos/index.html', {'vehiculos': vehiculos})

# Rgistrar nuevos vehiculos

def registrar_vehiculo(request):
    if request.method == 'POST':
        matricula = request.POST['matricula']
        marca = request.POST['marca']
        modelo = request.POST['modelo']
        color = request.POST['color']
        propietario_id = request.POST['propietario']
        errors = []
        
        # verificar errores posibles
        if Vehiculo.objects.filter(matricula=matricula).exists():
            errors.append = ["El vehículo con esta matrícula ya está registrado."]
        if len(matricula) != 7:
            errors.append("La matricula no es valida.")
        if errors:
            propietarios = Propietario.objects.all()
            return render(request, 'vehiculos/registrar.html', {'errors': errors, 'propietarios': propietarios})
        
        propietario = Propietario.objects.get(id=propietario_id)
        
        Vehiculo.objects.create(
            matricula=matricula,
            marca=marca,
            modelo=modelo,
            color=color,
            propietario=propietario
        )
        
        return redirect('vehiculos:index')

    propietarios = Propietario.objects.all()
    return render(request, 'vehiculos/registrar.html', {'propietarios': propietarios})



tarea3/condominio/templates/condominio/index.html

<head>
    
    <title></title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'condominio/css/index.css' %}">
</head>
<body>
    <h1>Gestión del Condominio</h1>
    <ul>
        <li><a href="{% url 'propietarios:index' %}">Propietarios</a></li>
        <li><a href="{% url 'vehiculos:index' %}">Vehiculos</a></li>
        <li><a href="{% url 'registros:index' %}">Registros de Entrada y Salida</a></li>
    </ul>
</body>

tarea3/propietarios/templates/propietarios/index.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'propietarios/css/index.css' %}">
    <title>Lista de Propietarios</title>
</head>
<body>
    <h1>Lista de Propietarios</h1>
    <div style="display: flex; justify-content: space-between;">
        <a href="{% url 'propietarios:registrar_propietario' %}">Agregar Nuevo Propietario</a>
        <a href="{% url 'condominio:index' %}">Pagina Principal</a>
    </div>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Departamento</th>
                <th>Teléfono</th>
                <th>Email</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for propietario in propietarios %}
            <tr>
                <td>{{ propietario.nombre_completo }}</td>
                <td>{{ propietario.numero_apartamento }}</td>
                <td>{{ propietario.numero_telefono }}</td>
                <td>{{ propietario.email }}</td>
                <td>

                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No hay propietarios registrados.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

tarea3/propietarios/templates/propietarios/registro.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'propietarios/css/registro.css' %}">
</head>

<body>
    <h1>Registrar Propietario</h1>
    {% if errors %}
        <div class="error">
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
        </div>
    {% endif %}
    <form method="POST" action="{% url 'propietarios:registrar_propietario' %}">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="nombre_completo">Nombre Completo:</label>
            <input type="text" name="nombre_completo" required>
        </div>
        <div class="form-group">
            <label for="numero_apartamento">Numero de Apartamento:</label>
            <input type="text" name="numero_apartamento" maxlength="3" required>
        </div>
        <div class="form-group">
            <label for="numero_telefono">Telefono:</label>
            <input type="number" name="numero_telefono"required>
        </div>
        <div class="form-group">
            <label for="email">Correo Electronico:</label>
            <input type="email" name="email" id="email" required>
        </div>
        <button type="submit">Registrar</button>
    </form>
    <a href="{% url 'propietarios:index' %}">Volver a la lista</a>
</body>
</html>

tarea3/registros/templates/registros/index.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'registros/css/index.css' %}">
    <title>Registros de Entrada y Salida</title>
</head>
<body>
    <h1>Registros de Entrada y Salida</h1>
    <a href="{% url 'condominio:index' %}">Ir a Pagina Principal</a>
    <div style="display: flex; justify-content: space-between;">
        <div>
            <h2>Registros de Entrada</h2>
            <a href="{% url 'registros:registrar_entrada' %}">Registrar Nueva Entrada</a>
            <table>
                <thead>
                    <tr>
                        <th>Matrícula</th>
                        <th>Fecha y Hora de Entrada</th>
                    </tr>
                </thead>
                <tbody>
                    {% for registro in registros_entrada %}
                    <tr>
                        <td>{{ registro.vehiculo.matricula }}</td>
                        <td>{{ registro.fecha_hora_entrada }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="2">No hay registros de entrada.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            <h2>Registros de Salida</h2>
            <a href="{% url 'registros:registrar_salida' %}">Registrar Nueva Salida</a>
            <table>
                <thead>
                    <tr>
                        <th>Matrícula</th>
                        <th>Fecha y Hora de Entrada</th>
                        <th>Fecha y Hora de Salida</th>
                    </tr>
                </thead>
                <tbody>
                    {% for registro in registros_salida %}
                    <tr>
                        <td>{{ registro.vehiculo.matricula }}</td>
                        <td>{{ registro.fecha_hora_entrada }}</td>
                        <td>{{ registro.fecha_hora_salida }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3">No hay registros de salida.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>

tarea3/registros/templates/registros/registrar_entrada.html


<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'registros/css/registro.css' %}">
    <title>Registrar Entrada</title>
</head>
<body>
    <h1>Registrar Entrada de Vehículo</h1>
    <form method="POST" action="{% url 'registros:registrar_entrada' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="vehiculo">Selecciona Vehículo:</label>
            <select name="vehiculo" id="vehiculo" required>
                <option value="">Seleccionar vehiculo</option>
                {% for vehiculo in vehiculos %}
                    <option value="{{ vehiculo.id }}">{{ vehiculo.matricula }} - {{ vehiculo.marca }} {{ vehiculo.modelo }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit">Registrar Entrada</button>
    </form>

    <a href="{% url 'registros:index' %}">Volver a registros</a>
</body>

tarea3/registros/templates/registros/registrar_salida.html

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'registros/css/registro.css' %}">
    <title>Registrar Salida</title>
</head>
<body>
    <h1>Registrar Salida</h1>
    
    {% if vehiculos %}
        <form method="POST" action="{% url 'registros:registrar_salida' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="matricula">Selecciona Vehículo:</label>
                <select name="matricula" id="matricula" required>
                    <option value="">Seleccionar Vehículo</option>
                    {% for vehiculo in vehiculos %}
                        <option value="{{ vehiculo.matricula }}">{{ vehiculo.matricula }} - {{ vehiculo.marca }} {{ vehiculo.modelo }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit">Registrar Salida</button>
        </form>
    {% else %}
        <p>No hay vehículos disponibles para registrar salida.</p>
    {% endif %}
    
    <a href="{% url 'registros:index' %}">Volver a Registros</a>
</body>

tarea3/vehiculos/templates/vehiculos/index.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'vehiculos/css/index.css' %}">
    <title>Lista de Vehículos</title>
</head>
<body>
    <h1>Lista de Vehículos</h1>
    <div style="display: flex; justify-content: space-between;">
        <a href="{% url 'vehiculos:registrar_vehiculo' %}">Agregar Nuevo Vehiculo</a>
        <a href="{% url 'condominio:index' %}">Ir a Pagina Principal</a>
    </div>
    <table>
        <thead>
            <tr>
                <th>Matrícula</th>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Color</th>
                <th>Propietario</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for vehiculo in vehiculos %}
            <tr>
                <td>{{ vehiculo.matricula }}</td>
                <td>{{ vehiculo.marca }}</td>
                <td>{{ vehiculo.modelo }}</td>
                <td>{{ vehiculo.color }}</td>
                <td>{{ vehiculo.propietario.nombre_completo }}</td>
                <td>
                    <!-- Aquí podrías añadir enlaces para editar o eliminar el vehículo -->
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No hay vehículos registrados.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

tarea3/vehiculos/templates/vehiculos/registrar.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'vehiculos/css/registrar.css' %}">
    <title>Registrar Vehículo</title>
</head>
<body>
    <h1>Registrar Vehículo</h1>
    {% if errors %}
        <div class="error">
            {% for error in errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </div>
    {% endif %}
    <form method="POST" action="{% url 'vehiculos:registrar_vehiculo' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="matricula">Matrícula:</label>
            <input type="text" name="matricula" maxlength="7" autocomplete="off" required>
        </div>
        <div class="form-group">
            <label for="marca">Marca:</label>
            <input type="text" name="marca" required>
        </div>
        <div class="form-group">
            <label for="modelo">Modelo:</label>
            <input type="text" name="modelo" required>
        </div>
        <div class="form-group">
            <label for="color">Color:</label>
            <input type="text" name="color" required>
        </div>
        <div class="form-group">
            <label for="propietario">Propietario:</label>
            <select name="propietario" required>
                <option value="">Seleccione un propietario</option>
                {% for propietario in propietarios %}
                    <option value="{{ propietario.id }}">{{ propietario.nombre_completo }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit">Registrar</button>
    </form>
    <a href="{% url 'vehiculos:index' %}">Volver a la lista</a>
</body>